MODEL: 3                    # 1: structure model, 2: inpaint model, 3: structure-inpaint model
VERBOSE: 1                    # turns on verbose mode in the output console
GPU: [0]                      # gpu ids

MAX_ITERS: 8e5 #8e6                # maximum number of iterations to train the model 8e6
LR: 0.0001                    # learning rate
BETA1: 0                      # adam optimizer beta1
BETA2: 0.999                  # adam optimizer beta2
LR_POLICY: constant           # the method to adjust learning rate (eg: constant|step)
STEP_SIZE: 100000             # Period of learning rate decay (only used when choosing "step" as the lr adjusment method)
GAMMA: 0.5                    # Multiplicative factor of learning rate decay. (only used when choosing "step" as the lr adjusment method)
INIT_TYPE: xavier             # initialization [gaussian/kaiming/xavier/orthogonal]

SAVE_INTERVAL: 3250 #2435 #4610 #4780 #3410          # how many iterations to wait before saving model
SAVE_LATEST: 3250 #2435 #4610 #4780 #3410             # how many iterations to wait before saving lastest model
SAMPLE_INTERVAL: 650 #1666 #2435 #1844 #2390 #682         # how many iterations to wait before sampling
SAMPLE_SIZE: 5                # number of images to sample
EVAL_INTERVAL: 3250 #4870 #18440 #23900 #3410          # how many iterations to wait before model evaluation
LOG_INTERVAL: 100             # how many iterations to wait before logging training status 
WHICH_ITER: latest            # which iterations to load

DIS_GAN_LOSS: lsgan           # type of gan loss 

STRUCTURE_L1: 4               # structure net parameter of l1 loss  
STRUCTURE_ADV_GEN: 1          # structure net parameter of gan loss  

FLOW_ADV_GEN: 1               # texture net parameter of gan loss  
FLOW_L1: 5                    # texture net parameter of l1 loss  
FLOW_CORRECTNESS: 0.25        # texture net parameter of sampling correctness loss  
VGG_STYLE: 250                # texture net parameter of vgg_style loss (Optional loss on stage_3)  
VGG_CONTENT: 0.1              # texture net parameter of vgg_content loss (Optional loss on stage_3) 


TRAIN_BATCH_SIZE: 9           # batch size
DATA_TRAIN_SIZE: 256          # image size for training 
DATA_TEST_SIZE: 256           # image size for testing (False for never resize)     default:False
DATA_FLIP: False              # filp image or not when training 
DATA_CROP: False #[537,537]   # crop size when training (False for never cro)
#DATA_MASK_TYPE: from_file     # mask type (random_bbox|random_free_form|from_file)
DATA_MASK_TYPE: random_bbox     # mask type (random_bbox|random_free_form|from_file)
STRUCTURE_MODE: L                 # OR RGB
DATA_RANDOM_BBOX_SETTING:     # parameters for random_bbox
  random_size: True          # random hole size according to shape [0.4*shape shape]
  shape: [80,80] #[80, 80]             # hole size
  min_shape: [15,15] #[15, 15]
  margin: [0, 0]              # minimum distance from the image boundary
  num: 3 #3
DATA_RANDOM_FF_SETTING:       # parameters for random_free_form
  mv: 5
  ma: 4.0
  ml: 50
  mbw: 20
DATA_MASK_FILE: '2w_mask' #'./3794_train_mask'   #./txt/irregular_mask.list #parameters for from_file
MASK_FILE_RANDOM: False

TEST_MASK_SIZE: 40
TEST_STEP: 40
TEST_EDGE: 20


# MURA
DATA_TRAIN_GT: ['./MURA_E_txt/gt_train.list']
DATA_TRAIN_STRUCTURE: ['./MURA_E_txt/structure_train.list']
DATA_VAL_GT: ['./MURA_E_txt/gt_testp.list']
DATA_VAL_STRUCTURE: ['./MURA_E_txt/structure_testp.list']
DATA_TEST_GT: ['./MURA_E_txt/gt_for_visual.list']
DATA_TEST_STRUCTURE: ['./MURA_E_txt/structure_for_visual.list']